const data = {
  data: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/qBx97wytqlyPqXATHqRgIVFxJRU.jpg",
        id: 436270,
        title: "Black Adam",
        original_language: "en",
        original_title: "Black Adam",
        overview:
          "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
        poster_path: "/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
        media_type: "movie",
        genre_ids: [28, 14, 878],
        popularity: 17030.072,
        release_date: "2022-10-19",
        video: false,
        vote_average: 7.283,
        vote_count: 2040,
      },
      {
        adult: false,
        backdrop_path: "/rfnmMYuZ6EKOBvQLp2wqP21v7sI.jpg",
        id: 774752,
        title: "The Guardians of the Galaxy Holiday Special",
        original_language: "en",
        original_title: "The Guardians of the Galaxy Holiday Special",
        overview:
          "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.",
        poster_path: "/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
        media_type: "movie",
        genre_ids: [35, 878, 12],
        popularity: 275.3,
        release_date: "2022-11-25",
        video: false,
        vote_average: 7.48,
        vote_count: 279,
      },
      {
        adult: false,
        backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
        id: 505642,
        title: "Black Panther: Wakanda Forever",
        original_language: "en",
        original_title: "Black Panther: Wakanda Forever",
        overview:
          "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
        poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
        media_type: "movie",
        genre_ids: [28, 12, 878],
        popularity: 2952.936,
        release_date: "2022-11-09",
        video: false,
        vote_average: 7.522,
        vote_count: 1047,
      },
      {
        adult: false,
        backdrop_path: "/kpUre8wWSXn3D5RhrMttBZa6w1v.jpg",
        id: 338958,
        title: "Disenchanted",
        original_language: "en",
        original_title: "Disenchanted",
        overview:
          "Disillusioned with life in the city, feeling out of place in suburbia, and frustrated that her happily ever after hasn’t been so easy to find, Giselle turns to the magic of Andalasia for help. Accidentally transforming the entire town into a real-life fairy tale and placing her family’s future happiness in jeopardy, she must race against time to reverse the spell and determine what happily ever after truly means to her and her family.",
        poster_path: "/4x3pt6hoLblBeHebUa4OyiVXFiM.jpg",
        media_type: "movie",
        genre_ids: [35, 10751, 14],
        popularity: 3475.144,
        release_date: "2022-11-16",
        video: false,
        vote_average: 7.412,
        vote_count: 385,
      },
      {
        adult: false,
        backdrop_path: "/o3mothJXDR9vLlZHpwyfFCycCNx.jpg",
        id: 668461,
        title: "Slumberland",
        original_language: "en",
        original_title: "Slumberland",
        overview:
          "A young girl discovers a secret map to the dreamworld of Slumberland, and with the help of an eccentric outlaw, she traverses dreams and flees nightmares, with the hope that she will be able to see her late father again.",
        poster_path: "/f18kgonrgr8YvEuvshExS4XBGL8.jpg",
        media_type: "movie",
        genre_ids: [10751, 14, 12, 18],
        popularity: 1686.35,
        release_date: "2022-11-09",
        video: false,
        vote_average: 7.945,
        vote_count: 256,
      },
      {
        adult: false,
        backdrop_path: "/fHDvGGPFry65ou79WLi6JsjCZrM.jpg",
        id: 632856,
        title: "Spirited",
        original_language: "en",
        original_title: "Spirited",
        overview:
          "Each Christmas Eve, the Ghost of Christmas Present selects one dark soul to be reformed by a visit from three spirits. But this season, he picked the wrong Scrooge. Clint Briggs turns the tables on his ghostly host until Present finds himself reexamining his own past, present and future.",
        poster_path: "/h3zAzTMs5EP3cKusOxFNGSFE1WI.jpg",
        media_type: "movie",
        genre_ids: [35],
        popularity: 788.222,
        release_date: "2022-11-10",
        video: false,
        vote_average: 7.413,
        vote_count: 143,
      },
      {
        adult: false,
        backdrop_path: "/olPXihyFeeNvnaD6IOBltgIV1FU.jpg",
        id: 882598,
        title: "Smile",
        original_language: "en",
        original_title: "Smile",
        overview:
          "After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.",
        poster_path: "/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg",
        media_type: "movie",
        genre_ids: [27, 9648, 53],
        popularity: 2425.949,
        release_date: "2022-09-23",
        video: false,
        vote_average: 6.8,
        vote_count: 928,
      },
      {
        adult: false,
        backdrop_path: "/7zQJYV02yehWrQN6NjKsBorqUUS.jpg",
        id: 724495,
        title: "The Woman King",
        original_language: "en",
        original_title: "The Woman King",
        overview:
          "The story of the Agojie, the all-female unit of warriors who protected the African Kingdom of Dahomey in the 1800s with skills and a fierceness unlike anything the world has ever seen, and General Nanisca as she trains the next generation of recruits and readies them for battle against an enemy determined to destroy their way of life.",
        poster_path: "/438QXt1E3WJWb3PqNniK0tAE5c1.jpg",
        media_type: "movie",
        genre_ids: [28, 18, 36],
        popularity: 1594.772,
        release_date: "2022-09-15",
        video: false,
        vote_average: 7.83,
        vote_count: 491,
      },
      {
        adult: false,
        backdrop_path: "/c1bz69r0v065TGFA5nqBiKzPDys.jpg",
        id: 830784,
        title: "Lyle, Lyle, Crocodile",
        original_language: "en",
        original_title: "Lyle, Lyle, Crocodile",
        overview:
          "When the Primm family moves to New York City, their young son Josh struggles to adapt to his new school and new friends. All of that changes when he discovers Lyle — a singing crocodile who loves baths, caviar and great music — living in the attic of his new home. But when Lyle’s existence is threatened by evil neighbor Mr. Grumps, the Primms must band together to show the world that family can come from the most unexpected places.",
        poster_path: "/irIS5Tn3TXjNi1R9BpWvGAN4CZ1.jpg",
        media_type: "movie",
        genre_ids: [35, 10751, 10402],
        popularity: 1257.595,
        release_date: "2022-10-07",
        video: false,
        vote_average: 7.38,
        vote_count: 50,
      },
      {
        adult: false,
        backdrop_path: "/rjlG7C5GZfXutoVoE3BJaYGUhk4.jpg",
        id: 829280,
        title: "Enola Holmes 2",
        original_language: "en",
        original_title: "Enola Holmes 2",
        overview:
          "Now a detective-for-hire like her infamous brother, Enola Holmes takes on her first official case to find a missing girl, as the sparks of a dangerous conspiracy ignite a mystery that requires the help of friends — and Sherlock himself — to unravel.",
        poster_path: "/tegBpjM5ODoYoM1NjaiHVLEA0QM.jpg",
        media_type: "movie",
        genre_ids: [9648, 12, 80],
        popularity: 1635.717,
        release_date: "2022-11-04",
        video: false,
        vote_average: 7.733,
        vote_count: 1150,
      },
      {
        adult: false,
        backdrop_path: "/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg",
        id: 361743,
        title: "Top Gun: Maverick",
        original_language: "en",
        original_title: "Top Gun: Maverick",
        overview:
          "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
        poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
        media_type: "movie",
        genre_ids: [28, 18],
        popularity: 690.619,
        release_date: "2022-05-24",
        video: false,
        vote_average: 8.344,
        vote_count: 4852,
      },
      {
        adult: false,
        backdrop_path: "/tP5PwKwDxnFu6FpM2hOWyqjf6Qy.jpg",
        id: 823766,
        title: "The Wonder",
        original_language: "en",
        original_title: "The Wonder",
        overview:
          "Haunted by her past, a nurse travels from England to a remote Irish village in 1862 to investigate a young girl's supposedly miraculous fast.",
        poster_path: "/4dX1LPGuZG0FSoP9y9SyDKLYicy.jpg",
        media_type: "movie",
        genre_ids: [9648, 53, 18],
        popularity: 254.771,
        release_date: "2022-11-02",
        video: false,
        vote_average: 6.747,
        vote_count: 221,
      },
      {
        adult: false,
        backdrop_path: "/198vrF8k7mfQ4FjDJsBmdQcaiyq.jpg",
        id: 76600,
        title: "Avatar: The Way of Water",
        original_language: "en",
        original_title: "Avatar: The Way of Water",
        overview:
          "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
        poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
        media_type: "movie",
        genre_ids: [878, 28, 12],
        popularity: 775.649,
        release_date: "2022-12-14",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/giveZjQGE4Pn3kJvsTn7uHqLjZS.jpg",
        id: 615952,
        title: "Armageddon Time",
        original_language: "en",
        original_title: "Armageddon Time",
        overview:
          "In 1980, Queens, New York, a young Jewish boy befriends a rebellious African-American classmate to the disapproval of his privileged family and begins to reckon with growing up in a world of inequality and prejudice.",
        poster_path: "/2bVjSEaLsUxUZ4Dutz9qRF5zXyd.jpg",
        media_type: "movie",
        genre_ids: [18],
        popularity: 153.622,
        release_date: "2022-10-28",
        video: false,
        vote_average: 6.923,
        vote_count: 84,
      },
      {
        adult: false,
        backdrop_path: "/79PcXPpbDWql74h8Y00mNwbYMbS.jpg",
        id: 664469,
        title: "Amsterdam",
        original_language: "en",
        original_title: "Amsterdam",
        overview:
          "In the 1930s, three friends—a doctor, a nurse, and an attorney—witness a murder, become suspects themselves and uncover one of the most outrageous plots in North American history.",
        poster_path: "/6sJcVzGCwrDCBMV0DU6eRzA2UxM.jpg",
        media_type: "movie",
        genre_ids: [80, 35, 36, 9648, 53],
        popularity: 200.237,
        release_date: "2022-09-27",
        video: false,
        vote_average: 6.128,
        vote_count: 375,
      },
      {
        adult: false,
        backdrop_path: "/3ibGaDmgTdXY448ENZmtHEmhP6o.jpg",
        id: 619730,
        title: "Don't Worry Darling",
        original_language: "en",
        original_title: "Don't Worry Darling",
        overview:
          "Alice and Jack are lucky to be living in the idealized community of Victory, the experimental company town housing the men who work for the top-secret Victory Project and their families. But when cracks in their idyllic life begin to appear, exposing flashes of something much more sinister lurking beneath the attractive façade, Alice can’t help questioning exactly what they’re doing in Victory, and why.",
        poster_path: "/60hrKYVq6Y1QRJeHNbYo3tHDcUd.jpg",
        media_type: "movie",
        genre_ids: [53, 9648, 878],
        popularity: 257.108,
        release_date: "2022-09-21",
        video: false,
        vote_average: 6.914,
        vote_count: 1038,
      },
      {
        adult: false,
        backdrop_path: "/mqsPyyeDCBAghXyjbw4TfEYwljw.jpg",
        id: 49046,
        title: "All Quiet on the Western Front",
        original_language: "de",
        original_title: "Im Westen nichts Neues",
        overview:
          "Paul Baumer and his friends Albert and Muller, egged on by romantic dreams of heroism, voluntarily enlist in the German army. Full of excitement and patriotic fervour, the boys enthusiastically march into a war they believe in. But once on the Western Front, they discover the soul-destroying horror of World War I.",
        poster_path: "/hYqOjJ7Gh1fbqXrxlIao1g8ZehF.jpg",
        media_type: "movie",
        genre_ids: [10752, 18, 28],
        popularity: 1330.203,
        release_date: "2022-10-07",
        video: false,
        vote_average: 7.802,
        vote_count: 932,
      },
      {
        adult: false,
        backdrop_path: "/527Kxta1PjtovdFbsBe3vxO6Zfw.jpg",
        id: 718930,
        title: "Bullet Train",
        original_language: "en",
        original_title: "Bullet Train",
        overview:
          "Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
        poster_path: "/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
        media_type: "movie",
        genre_ids: [28, 35, 53],
        popularity: 819.851,
        release_date: "2022-07-03",
        video: false,
        vote_average: 7.509,
        vote_count: 2449,
      },
      {
        adult: false,
        backdrop_path: "/dsWxCsAdsocMNQFbhe39ynAOhBa.jpg",
        id: 1049233,
        title: "Lesson Plan",
        original_language: "pl",
        original_title: "Plan lekcji",
        overview:
          "After a teacher dies, his best friend — a former cop — takes a job at the school where he worked to confront the gang he thinks was responsible.",
        poster_path: "/wawP3mOUeRBrAtnbPwWK5eFaMdV.jpg",
        media_type: "movie",
        genre_ids: [80, 53],
        popularity: 56.703,
        release_date: "2022-11-23",
        video: false,
        vote_average: 6.2,
        vote_count: 20,
      },
      {
        adult: false,
        backdrop_path: "/1AsP4UAv6hCGXUcH8GqMwd5KmCN.jpg",
        id: 497828,
        title: "Triangle of Sadness",
        original_language: "en",
        original_title: "Triangle of Sadness",
        overview:
          "A celebrity model couple are invited on a luxury cruise for the uber-rich, helmed by an unhinged captain. What first appeared Instagrammable ends catastrophically, leaving the survivors stranded on a desert island and fighting for survival.",
        poster_path: "/fgy78BLl0gk8OzTWHZyGrSlIEON.jpg",
        media_type: "movie",
        genre_ids: [35, 18],
        popularity: 101.973,
        release_date: "2022-09-23",
        video: false,
        vote_average: 7.6,
        vote_count: 308,
      },
    ],
    total_pages: 1000,
    total_results: 20000,
  },
  status: 200,
  statusText: "OK",
  headers: {
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "*",
    age: "313",
    "alt-svc": 'h3=":443"; ma=86400',
    "cache-control": "public, max-age=28800",
    "content-encoding": "br",
    "content-type": "application/json;charset=utf-8",
    date: "Mon, 28 Nov 2022 13:51:45 GMT",
    etag: 'W/"b6623b407b72faf4924412797e1e7e25"',
    server: "openresty",
    vary: "Accept-Encoding,Accept-Encoding,Accept-Encoding",
    via: "1.1 7831077905969c90ee4e09ffe271ccc8.cloudfront.net (CloudFront)",
    "x-amz-cf-id": "d5zWFgsRWf5Hb7YeZgW73pqqzixhQ8IOVagJgnKw1xYOPf77oJ1jIQ==",
    "x-amz-cf-pop": "WAW51-P1",
    "x-cache": "Hit from cloudfront",
    "x-firefox-http3": "h3",
    "x-memc": "HIT",
    "x-memc-age": "382",
    "x-memc-expires": "218",
    "x-memc-key": "f62c852e7921e9600db4376157b76c9df1f37ee9",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    adapter: ["xhr", "http"],
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {},
    headers: {
      Accept: "application/json, text/plain, */*",
      "Content-Type": null,
    },
    params: {
      api_key: "a8c13239d5351cd341496e4bdbeed27b",
    },
    method: "get",
    url: "https://api.themoviedb.org/3/trending/movie/week",
  },
  request: {},
};
